// Typed route constants — every Link/redirect added under src/app/(app)
// should use these instead of raw path strings.

export const ROUTES = {
  home: "/",
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  admin: "/admin",
  profile: "/profile",
  pos: {
    root: "/pos",
    hold: "/pos/hold",
    close: "/pos/close",
  },
  dashboard: "/dashboard",
  products: "/products",
  productsNew: "/products/new",
  productDetail: (id: string) => `/products/${id}`,
  catalogue: {
    import: "/products/import",
    importUpdate: "/products/import-update",
    openingStock: "/products/opening-stock",
    printLabels: "/products/print-labels",
    countStock: "/products/count-stock",
    categories: "/products/categories",
    brands: "/products/brands",
    units: "/products/units",
    batches: "/products/batches",
  },
  inventory: {
    root: "/inventory",
    new: "/inventory/new",
    detail: (id: string) => `/inventory/${id}`,
    alerts: "/inventory/alerts",
    movements: "/inventory/movements",
    transfers: "/inventory/transfers",
  },
  purchases: {
    root: "/purchases",
    new: "/purchases/new",
    detail: (id: string) => `/purchases/${id}`,
    returns: "/purchases/returns",
  },
  sales: {
    root: "/sales",
    detail: (id: string) => `/sales/${id}`,
  },
  store: {
    root: "/store",
    online: "/store/online",
    settings: "/store/settings",
    orders: "/store/orders",
    collections: "/store/collections",
    banners: "/store/banners",
    subscribers: "/store/subscribers",
    messages: "/store/messages",
    inviteCodes: "/store/invite-codes",
    pendingCustomers: "/store/pending-customers",
  },
  suppliers: "/suppliers",
  reports: "/reports",
  discounts: "/discounts",
  users: {
    root: "/users",
    new: "/users/new",
    edit: (id: string) => `/users/${id}`,
    permissions: "/users/permissions",
    permissionsNew: "/users/permissions/new",
  },
  settings: {
    root: "/settings",
    hardware: "/settings/hardware",
  },
} as const;
